server {
    listen 80;
    server_name _;

    # Interface (fichiers statiques)
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Les appels /api/* sont transmis à l'Ambassadeur Python
    location /api/ {
        proxy_pass http://ambassadeur:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 10M;
        proxy_read_timeout 60s;
    }
}